// Generated by CoffeeScript 1.12.7
(function() {
  var Component_ImageAnimation,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  Component_ImageAnimation = (function(superClass) {
    extend(Component_ImageAnimation, superClass);


    /**
    * Executes a image-based animation.
    *
    * @module gs
    * @class Component_ImageAnimation
    * @extends gs.Component_Animation
    * @memberof gs
    * @constructor
     */

    function Component_ImageAnimation(data) {
      Component_ImageAnimation.__super__.constructor.apply(this, arguments);

      /**
      * The images to animate through.
      * @property images
      * @type string[]
       */
      this.images = (data != null ? data.images : void 0) || [];

      /**
      * The easing-object used for the animation.
      * @property easing
      * @type gs.Easing
       */
      this.easing = new gs.Easing(null, data != null ? data.easing : void 0);
    }


    /**
    * Serializes the image-animation into a data-bundle.
    *
    * @method toDataBundle
     */

    Component_ImageAnimation.prototype.toDataBundle = function() {
      return {
        easing: this.easing,
        images: this.images
      };
    };


    /**
    * Updates the image-animation.
    *
    * @method update
     */

    Component_ImageAnimation.prototype.update = function() {
      Component_ImageAnimation.__super__.update.apply(this, arguments);
      if (!this.easing.isRunning) {
        return;
      }
      this.easing.updateValue();
      this.object.image = this.images[Math.round(this.easing.value)];
      if (!this.easing.isRunning) {
        return typeof this.callback === "function" ? this.callback(this.object, this) : void 0;
      }
    };


    /**
    * A simple image animation runs from left to right using the game object's
    * image-property.
    *
    * @method changeImages
    * @param {Array} images An array of image names.
    * @param {number} duration The duration in frames.
    * @param {Object} easingType The easing-type.
    * @param {function} [callback] An optional callback called if blending is finished.
     */

    Component_ImageAnimation.prototype.start = function(images, duration, easingType, callback) {
      this.callback = callback;
      this.images = images;
      this.easing.type = easingType || gs.Easings.EASE_LINEAR[gs.EasingTypes.EASE_IN];
      return this.easing.startValue(0, images.length - 1, duration);
    };

    return Component_ImageAnimation;

  })(gs.Component_Animation);

  gs.Component_ImageAnimation = Component_ImageAnimation;

}).call(this);
