// Generated by CoffeeScript 1.12.7
(function() {
  ui.UiFactory.layouts.cgGalleryImageLayout = {
    "type": "ui.FreeLayout",
    "orientation": "vertical",
    "preload": {
      "graphics": [
        {
          "path": $(function() {
            return [$tempFields.selectedImage];
          }),
          "image": $(function() {
            return o;
          })
        }, {
          "path": ["locked"],
          "image": $(function() {
            return o;
          })
        }
      ]
    },
    "frame": [0, 0, Graphics.width, Graphics.height],
    "controls": [
      {
        "type": "ui.Image",
        "frame": [0, 0],
        "formulas": [
          $(function() {
            return o.image = $tempFields.selectedImage;
          })
        ],
        "action": {
          "name": "executeFormulas",
          "params": [
            $(function() {
              return $backButton.visible = !$backButton.visible;
            })
          ]
        }
      }, {
        "type": "ui.Button",
        "id": "backButton",
        "params": {
          "text": {
            "lcId": "B0FD4BF121D9E44E7589CDD35869F86F2227",
            "defaultText": "Back"
          },
          "action": {
            "name": "previousLayout"
          }
        },
        "frame": [Graphics.width - 170, Graphics.height - 65, 150, 45],
        "order": 1
      }
    ]
  };

}).call(this);
