// Generated by CoffeeScript 1.12.7
(function() {
  ui.UiFactory.layouts.webStartLayout = {
    "type": "ui.FreeLayout",
    "frame": [0, 0, Graphics.width, Graphics.height],
    "component": {
      "className": "Component_WebStartBehavior"
    },
    "controls": [
      {
        "type": "ui.Image",
        "frame": [0, 0, Graphics.width, Graphics.height],
        "image": "web-start-screen"
      }
    ]
  };

}).call(this);
