// Generated by CoffeeScript 1.12.7
(function() {
  var Object_MessageArea,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  Object_MessageArea = (function(superClass) {
    extend(Object_MessageArea, superClass);

    Object_MessageArea.objectCodecBlackList = ["parent", "layout", "message"];

    Object_MessageArea.toDataBundle = function(object, context) {
      return {
        message: gs.ObjectCodec.encode(object.message, context),
        layout: {
          dstRect: gs.Rect.fromObject(object.layout.dstRect)
        }
      };
    };


    /**
    * A game object used for message areas in a scene.
    *
    * @module gs
    * @class Object_MessageArea
    * @extends gs.Object_Visual
    * @memberof gs
    * @constructor
     */

    function Object_MessageArea(parent, data, type) {
      Object_MessageArea.__super__.constructor.call(this, data);
      this.layout = null;
      this.message = null;
      this.addComponent(new gs.Component_Container());
    }

    return Object_MessageArea;

  })(gs.Object_Visual);

  gs.Object_MessageArea = Object_MessageArea;

}).call(this);
