// Generated by CoffeeScript 1.12.7
(function() {
  ui.UiFactory.customTypes["ui.SettingsOptionSet"] = {
    "type": "ui.StackLayout",
    "sizeToFit": true,
    "orientation": "vertical",
    "margin": [10, 10, 0, 0],
    "controls": [
      {
        "type": "ui.Text",
        "text": function() {
          return p.label;
        },
        "styles": ["regularUIText"],
        "frame": [0, 0, 300, gs.UIConstants.OPTION_BUTTON_H - 30]
      }, {
        "type": "ui.OptionButtonSet",
        "frame": [80, 0, 330, gs.UIConstants.OPTION_BUTTON_H],
        "params": {
          "actions": [],
          "write": (function() {
            return p.write;
          }),
          "read": (function() {
            return p.read;
          }),
          "max": 100,
          "onLabel": (function() {
            return p.onLabel || lcsi("DB87E66F8299B549E56B2F048040DA406BCC");
          }),
          "onAction": (function() {
            return p.onAction;
          }),
          "offLabel": (function() {
            return p.offLabel || lcsi("2D23328A3B4F80462E7AB2F8CD3996B20665");
          }),
          "offAction": (function() {
            return p.offAction;
          }),
          "group": (function() {
            return p.group;
          })
        }
      }
    ]
  };

}).call(this);
