// Generated by CoffeeScript 1.12.7
(function() {
  ui.UiFactory.customTypes["ui.InputNumberBox"] = {
    "type": "ui.FreeLayout",
    "frame": [0, 0, Graphics.width, Graphics.height],
    "controls": [
      {
        "type": "ui.FreeLayout",
        "sizeToFit": true,
        "alignmentX": "center",
        "frame": [0, 10],
        "zIndex": 1000,
        "controls": [
          {
            "type": "ui.FreeLayout",
            "sizeToFit": true,
            "controls": [
              {
                "type": "ui.Window",
                "frame": [0, 0, "MAX($tempFields.digits * 110, 460)", 470]
              }, {
                "type": "ui.Panel",
                "style": "windowSubPanel",
                "frame": ["MAX($tempFields.digits * 110, 460) - 130", 180, 130, 470 - 160],
                "zIndex": 10
              }, {
                "type": "ui.Panel",
                "style": "windowContentSeparator",
                "frame": [0, 180, "MAX($tempFields.digits * 110, 460)", 1],
                "zIndex": 10
              }, {
                "type": "ui.Text",
                "styles": ["regularUIText"],
                "sizeToFit": true,
                "text": "Number",
                "zIndex": 10,
                "frame": [20, 15]
              }, {
                "type": "ui.StackLayout",
                "components": [
                  {
                    "id": "numberInput",
                    "type": "Component_NumberInput",
                    "params": {
                      "digits": $(function() {
                        return $tempFields.digits;
                      })
                    }
                  }
                ],
                "sizeToFit": true,
                "id": "numberField",
                "zIndex": 10,
                "alignmentX": "center",
                "frame": [12, 50],
                "dataField": $(function() {
                  return $tempFields.digits;
                }),
                "template": {
                  "type": "ui.FreeLayout",
                  "margin": [5, 5, 5, 5],
                  "sizeToFit": true,
                  "controls": [
                    {
                      "type": "ui.Image",
                      "image": "entrybox"
                    }, {
                      "type": "ui.Text",
                      "frame": [0, 0],
                      "sizeToFit": true,
                      "alignmentX": "center",
                      "alignmentY": "center",
                      "style": "numberInputEntryText",
                      "text": "0"
                    }
                  ]
                }
              }
            ]
          }, {
            "type": "ui.GridLayout",
            "sizeToFit": true,
            "rows": 4,
            "columns": 3,
            "alignmentY": 0,
            "frame": [30, 185],
            "cellSpacing": [0, 0, 40, 0],
            "controls": [
              {
                "type": "ui.Number",
                "params": {
                  "text": "1",
                  "number": 1,
                  "target": $(function() {
                    return 'numberField.numberInput';
                  })
                }
              }, {
                "type": "ui.Number",
                "params": {
                  "text": "2",
                  "number": 2,
                  "target": $(function() {
                    return 'numberField.numberInput';
                  })
                }
              }, {
                "type": "ui.Number",
                "params": {
                  "text": "3",
                  "number": 3,
                  "target": $(function() {
                    return 'numberField.numberInput';
                  })
                }
              }, {
                "type": "ui.Number",
                "params": {
                  "text": "4",
                  "number": 4,
                  "target": $(function() {
                    return 'numberField.numberInput';
                  })
                }
              }, {
                "type": "ui.Number",
                "params": {
                  "text": "5",
                  "number": 5,
                  "target": $(function() {
                    return 'numberField.numberInput';
                  })
                }
              }, {
                "type": "ui.Number",
                "params": {
                  "text": "6",
                  "number": 6,
                  "target": $(function() {
                    return 'numberField.numberInput';
                  })
                }
              }, {
                "type": "ui.Number",
                "params": {
                  "text": "7",
                  "number": 7,
                  "target": $(function() {
                    return 'numberField.numberInput';
                  })
                }
              }, {
                "type": "ui.Number",
                "params": {
                  "text": "8",
                  "number": 8,
                  "target": $(function() {
                    return 'numberField.numberInput';
                  })
                }
              }, {
                "type": "ui.Number",
                "params": {
                  "text": "9",
                  "number": 9,
                  "target": $(function() {
                    return 'numberField.numberInput';
                  })
                }
              }, {
                "type": "ui.Number",
                "params": {
                  "text": "0",
                  "number": 0,
                  "target": $(function() {
                    return 'numberField.numberInput';
                  })
                }
              }
            ]
          }, {
            "type": "ui.NumberBackspace",
            "params": {
              "target": $(function() {
                return 'numberField.numberInput';
              })
            },
            "frame": ["100% - 120", 260]
          }, {
            "type": "ui.NumberAccept",
            "frame": ["100% - 120", 200]
          }
        ]
      }
    ]
  };

  ui.UiFactory.customTypes["ui.Number"] = {
    "type": "ui.FreeLayout",
    "sizeToFit": true,
    "controls": [
      {
        "type": "ui.Frame",
        "style": "selectableWindowShadow",
        "images": ["", "selection", "", "", ""],
        "zIndex": 5000,
        "padding": [-16, -16, -16, -16],
        "frame": [0, 0, 70, 70],
        "actions": [
          {
            "name": "action_addNumber",
            "target": (function() {
              return p.target;
            }),
            "params": {
              "number": (function() {
                return p.number;
              })
            }
          }
        ]
      }, {
        "type": "ui.Text",
        "sizeToFit": true,
        "alignmentX": "center",
        "alignmentY": "center",
        "style": "numberInputDigitText",
        "text": (function() {
          return p.text;
        }),
        "zIndex": 5000
      }
    ]
  };

  ui.UiFactory.customTypes["ui.NumberBackspace"] = {
    "type": "ui.FreeLayout",
    "sizeToFit": true,
    "controls": [
      {
        "type": "ui.Text",
        "sizeToFit": true,
        "styles": ["regularUIText"],
        "text": "Back",
        "zIndex": 5000,
        "action": {
          "name": "action_removeNumber",
          "target": (function() {
            return p.target;
          }),
          "params": {
            "number": (function() {
              return p.number;
            })
          }
        }
      }
    ]
  };

  ui.UiFactory.customTypes["ui.NumberAccept"] = {
    "type": "ui.FreeLayout",
    "sizeToFit": true,
    "controls": [
      {
        "type": "ui.Text",
        "sizeToFit": true,
        "styles": ["regularUIText"],
        "text": "Confirm",
        "zIndex": 5000,
        "action": {
          "name": "emitEvent",
          "params": {
            "name": "accept",
            "source": $(function() {
              return o.parent.parent.parent;
            }),
            "data": {
              "number": $(function() {
                return $numberField.numberInput.number;
              })
            }
          }
        }
      }
    ]
  };

}).call(this);
