// Generated by CoffeeScript 1.12.7
(function() {
  ui.UiFactory.customTypes["ui.Window"] = {
    "type": "ui.FreeLayout",
    "controls": [
      {
        "type": "ui.Frame",
        "inheritProperties": true,
        "image": "dropshadow",
        "style": "windowShadow",
        "frame": [0, 0, "100%", "100%"],
        "zIndex": 0,
        "order": 0
      }, {
        "type": "ui.Image",
        "inheritProperties": true,
        "style": "windowTilePattern",
        "frame": [0, 0, "100%", "100%"],
        "opacity": function() {
          var ref;
          return (ref = p.backgroundOpacity) != null ? ref : 255;
        },
        "zIndex": 1,
        "order": 1
      }, {
        "type": "ui.Image",
        "inheritProperties": true,
        "style": "windowStretchPattern",
        "frame": [0, 0, "100%", "100%"],
        "opacity": function() {
          var ref;
          return (ref = p.backgroundOpacity) != null ? ref : 255;
        },
        "zIndex": 2,
        "order": 2
      }, {
        "type": "ui.Frame",
        "inheritProperties": true,
        "style": "windowFrame",
        "frame": [0, 0, "100%", "100%"],
        "zIndex": 3,
        "order": 3,
        "action": function() {
          return p.action;
        }
      }
    ]
  };

}).call(this);
