// Generated by CoffeeScript 1.12.7
(function() {
  ui.UiFactory.customTypes["ui.Button"] = {
    "type": "ui.FreeLayout",
    "style": "button",
    "controls": [
      {
        "type": "ui.SelectableWindow",
        "frame": [0, 0, "100%", "100%"],
        "margin": [0, 0, 0, 30],
        "inheritProperties": true,
        "params": {
          "actions": function() {
            return p.actions;
          },
          "action": function() {
            if (!p.actions) {
              return Object.mixin({
                "sound": $dataFields.database.system.menuSelectSound
              }, p.action);
            } else {
              return null;
            }
          },
          "sound": function() {
            return p.sound;
          }
        },
        "zIndex": 4999
      }, {
        "type": "ui.Text",
        "executeFieldFormulas": true,
        "inheritProperties": true,
        "sizeToFit": true,
        "style": "buttonText",
        "frame": [0, 0],
        "text": function() {
          return p.text;
        },
        "zIndex": 5100
      }
    ]
  };

  ui.UiFactory.customTypes["ui.BackButton"] = {
    "type": "ui.Button",
    "params": {
      "text": function() {
        return (typeof p !== "undefined" && p !== null ? p.text : void 0) || {
          lcId: "B0FD4BF121D9E44E7589CDD35869F86F2227",
          defaultText: "Back"
        };
      },
      "actions": [
        {
          "sound": (function() {
            return $dataFields.database.system.menuSelectSound;
          }),
          "event": "onMouseClick",
          "name": "saveSettings"
        }, {
          "event": "onMouseClick",
          "name": "previousLayout"
        }
      ],
      "sound": function() {
        return $dataFields.database.system.menuCancelSound;
      }
    }
  };

}).call(this);
