// Generated by CoffeeScript 1.12.7
(function() {
  ui.UiFactory.customTypes["ui.MessageOptionButton"] = {
    "type": "ui.StackLayout",
    "sizeToFit": true,
    "style": "messageOptionButton",
    "controls": [
      {
        "type": "ui.Image",
        "inheritProperties": true,
        "selectable": true,
        "style": "messageOptionButton",
        "image": gs.UIConstants.OPTION_BUTTON_MSG_IMAGE_OFF,
        "actions": [
          {
            "name": "executeFormulas",
            "params": [
              $(function() {
                return o.parent.params.write.exec();
              }), $(function() {
                return o.parent.controls[1].ui.selected = o.ui.selected;
              })
            ]
          }, function() {
            return p.action1;
          }, function() {
            return p.action2;
          }
        ],
        "margin": [0, 0, 11, 0]
      }, {
        "type": "ui.Text",
        "inheritProperties": true,
        "sizeToFit": true,
        "style": "regularUIText",
        "selectable": true,
        "actions": [
          {
            "name": "executeFormulas",
            "params": [
              $(function() {
                return o.parent.params.write.exec();
              }), $(function() {
                return o.parent.controls[0].ui.selected = !o.parent.controls[0].ui.selected;
              }), $(function() {
                return o.ui.selected = o.parent.controls[0].ui.selected;
              })
            ]
          }, function() {
            return p.action1;
          }, function() {
            return p.action2;
          }
        ],
        "alignmentY": "center",
        "text": function() {
          return p.label;
        }
      }
    ]
  };

}).call(this);
